# Generated by Django 5.0.6 on 2024-06-11 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2024, 6, 11, 17, 22, 53, 728038)),
        ),
    ]
